name: Build Chrome Extension

# 工作流的触发条件
on:
  push:
    branches: [ "main" ] # 当代码推送到 main 分支时触发
  pull_request:
    branches: [ "main" ] # 当有 PR 合并到 main 分支时也触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机

    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 第二步：使用社区的打包 Action
      - name: Build CRX
        uses: stefanzweifel/chrome-extension-builder-action@v1
        with:
          # 你的扩展程序根目录（如果 manifest.json 就在根目录，这里就是 '.'）
          path: src
          
          # 你的私有密钥，从 GitHub Secrets 读取
          private_key: ${{ secrets.CRX_PRIVATE_KEY }}
          
          # 打包后的文件名
          zip_name: FreeTimezone.zip  # 这个 Action 会先生成一个 zip 包
          crx_name: FreeTimezone.crx  # 然后再生成 crx 包

      # 第三步（可选）：将打包好的文件作为产物上传
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-build
          path: |
            FreeTimezone.zip
            FreeTimezone.crx