name: Build Chrome Extension

# 工作流的触发条件
on:
  push:
    branches: [ "main" ] # 当代码推送到 main 分支时触发
  pull_request:
    branches: [ "main" ] # 当有 PR 合并到 main 分支时也触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机

    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 第二步：安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 第三步：创建 ZIP 包
      - name: Create ZIP package
        run: |
          cd src
          zip -r ../FreeTimezone.zip .
          cd ..

      # 第四步：安装 Chrome 扩展打包工具
      - name: Install crx3
        run: npm install -g crx3

      # 第五步：生成 CRX 包（如果有私钥）
      - name: Build CRX
        if: ${{ env.CRX_PRIVATE_KEY != '' }}
        env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        run: |
          echo "$CRX_PRIVATE_KEY" > private-key.pem
          crx3 src -p private-key.pem -o FreeTimezone.crx
          rm private-key.pem

      # 第三步（可选）：将打包好的文件作为产物上传
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-build
          path: |
            FreeTimezone.zip
            FreeTimezone.crx